### ISSUE TITLE
Support for Java 11

### ISSUE THREAD

**Issue by thomas-ngrok** [ngrok/ngrok-java#1]
Is it possible to also compile the `ngrok-java` and `ngrok-java-native` libraries using Java 11? This would make the adoption of the new Jenkins plugin version easier since it wouldn’t require a Java bump from 11 to 17.

**Comment by CarlAmko** [comment]
@thomas-ngrok Just FYI, going to close this in favor of #9. We ultimately plan to be able to support both Java 17 and 11.
